url = "https://github.com/sharkdp/bat/archive/refs/tags/v0.18.0.tar.gz"

[dependencies]
dependencies = []
buildDependencies = ["rust"]
optionalDependencies = []

[binaries]
supportsRosetta = true

[[binaries.intel]]
url = "https://github.com/sharkdp/bat/releases/download/v0.18.0/bat-v0.18.0-x86_64-apple-darwin.tar.gz"
binPath = "bat"
sha256 = "86583f06b490278fed45407f34afb17d674a8c8c6e8c70bcee5e9bcbf7f3f548"
supportedVersions = ["all"]

[[binaries.silicon]]
url = "https://packages.stewproject.sh/bat/0.18.0/bat-0.18.0-silicon.tar.xz"
sha256 = "5128427093c5ae4789b92938a1e3608875962be58c474e0dc325e69c7523436b"
supportedVersions = ["all"]
